/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.33
 * Generated at: 2020-06-10 01:04:05 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.user;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class register_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Register</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"register_account\">\r\n");
      out.write("          \t<div class=\"wrap\">\r\n");
      out.write("    \t      <h4 class=\"title\">Create an Account</h4>\r\n");
      out.write("    \t\t   <form>\r\n");
      out.write("    \t\t\t <div class=\"col_1_of_2 span_1_of_2\">\r\n");
      out.write("\t\t   \t\t\t <div><input type=\"text\" value=\"Name\" onfocus=\"this.value = '';\" onblur=\"if (this.value == '') {this.value = 'Name';}\"></div>\r\n");
      out.write("\t\t    \t\t\t<div><input type=\"text\" value=\"Company Name\" onfocus=\"this.value = '';\" onblur=\"if (this.value == '') {this.value = 'Company Name';}\"></div>\r\n");
      out.write("\t\t    \t\t\t<div><input type=\"text\" value=\"E-Mail\" onfocus=\"this.value = '';\" onblur=\"if (this.value == '') {this.value = 'E-Mail';}\"></div>\r\n");
      out.write("\t\t    \t\t\t<div><input type=\"text\" value=\"password\" onfocus=\"this.value = '';\" onblur=\"if (this.value == '') {this.value = 'password';}\"></div>\r\n");
      out.write("\t\t    \t </div>\r\n");
      out.write("\t\t    \t  <div class=\"col_1_of_2 span_1_of_2\">\t\r\n");
      out.write("\t\t    \t\t<div><input type=\"text\" value=\"Address\" onfocus=\"this.value = '';\" onblur=\"if (this.value == '') {this.value = 'Address';}\"></div>\r\n");
      out.write("\t\t    \t\t<div><select id=\"country\" name=\"country\" onchange=\"change_country(this.value)\" class=\"frm-field required\">\r\n");
      out.write("\t\t            <option value=\"null\">Select a Country</option>         \r\n");
      out.write("\t\t            <option value=\"AX\">Åland Islands</option>\r\n");
      out.write("\t\t            <option value=\"AF\">Afghanistan</option>\r\n");
      out.write("\t\t            <option value=\"AL\">Albania</option>\r\n");
      out.write("\t\t            <option value=\"DZ\">Algeria</option>\r\n");
      out.write("\t\t            <option value=\"AS\">American Samoa</option>\r\n");
      out.write("\t\t            <option value=\"AD\">Andorra</option>\r\n");
      out.write("\t\t            <option value=\"AO\">Angola</option>\r\n");
      out.write("\t\t            <option value=\"AI\">Anguilla</option>\r\n");
      out.write("\t\t            <option value=\"AQ\">Antarctica</option>\r\n");
      out.write("\t\t            <option value=\"AG\">Antigua And Barbuda</option>\r\n");
      out.write("\t\t            <option value=\"AR\">Argentina</option>\r\n");
      out.write("\t\t            <option value=\"AM\">Armenia</option>\r\n");
      out.write("\t\t            <option value=\"AW\">Aruba</option>\r\n");
      out.write("\t\t            <option value=\"AU\">Australia</option>\r\n");
      out.write("\t\t            <option value=\"AT\">Austria</option>\r\n");
      out.write("\t\t            <option value=\"AZ\">Azerbaijan</option>\r\n");
      out.write("\t\t            <option value=\"BS\">Bahamas</option>\r\n");
      out.write("\t\t            <option value=\"BH\">Bahrain</option>\r\n");
      out.write("\t\t            <option value=\"BD\">Bangladesh</option>\r\n");
      out.write("\t\t            <option value=\"BB\">Barbados</option>\r\n");
      out.write("\t\t            <option value=\"BY\">Belarus</option>\r\n");
      out.write("\t\t            <option value=\"BE\">Belgium</option>\r\n");
      out.write("\t\t            <option value=\"BZ\">Belize</option>\r\n");
      out.write("\t\t            <option value=\"BJ\">Benin</option>\r\n");
      out.write("\t\t            <option value=\"BM\">Bermuda</option>\r\n");
      out.write("\t\t            <option value=\"BT\">Bhutan</option>\r\n");
      out.write("\t\t            <option value=\"BO\">Bolivia</option>\r\n");
      out.write("\t\t            <option value=\"BA\">Bosnia and Herzegovina</option>\r\n");
      out.write("\t\t            <option value=\"BW\">Botswana</option>\r\n");
      out.write("\t\t            <option value=\"BV\">Bouvet Island</option>\r\n");
      out.write("\t\t            <option value=\"BR\">Brazil</option>\r\n");
      out.write("\t\t            <option value=\"IO\">British Indian Ocean Territory</option>\r\n");
      out.write("\t\t            <option value=\"BN\">Brunei</option>\r\n");
      out.write("\t\t            <option value=\"BG\">Bulgaria</option>\r\n");
      out.write("\t\t            <option value=\"BF\">Burkina Faso</option>\r\n");
      out.write("\t\t            <option value=\"BI\">Burundi</option>\r\n");
      out.write("\t\t            <option value=\"KH\">Cambodia</option>\r\n");
      out.write("\t\t            <option value=\"CM\">Cameroon</option>\r\n");
      out.write("\t\t            <option value=\"CA\">Canada</option>\r\n");
      out.write("\t\t            <option value=\"CV\">Cape Verde</option>\r\n");
      out.write("\t\t            <option value=\"KY\">Cayman Islands</option>\r\n");
      out.write("\t\t            <option value=\"CF\">Central African Republic</option>\r\n");
      out.write("\t\t            <option value=\"TD\">Chad</option>\r\n");
      out.write("\t\t            <option value=\"CL\">Chile</option>\r\n");
      out.write("\t\t            <option value=\"CN\">China</option>\r\n");
      out.write("\t\t            <option value=\"CX\">Christmas Island</option>\r\n");
      out.write("\t\t            <option value=\"CC\">Cocos (Keeling) Islands</option>\r\n");
      out.write("\t\t            <option value=\"CO\">Colombia</option>\r\n");
      out.write("\t\t            <option value=\"KM\">Comoros</option>\r\n");
      out.write("\t\t            <option value=\"CG\">Congo</option>\r\n");
      out.write("\t\t            <option value=\"CD\">Congo, Democractic Republic</option>\r\n");
      out.write("\t\t            <option value=\"CK\">Cook Islands</option>\r\n");
      out.write("\t\t            <option value=\"CR\">Costa Rica</option>\r\n");
      out.write("\t\t            <option value=\"CI\">Cote D'Ivoire (Ivory Coast)</option>\r\n");
      out.write("\t\t            <option value=\"HR\">Croatia (Hrvatska)</option>\r\n");
      out.write("\t\t            <option value=\"CU\">Cuba</option>\r\n");
      out.write("\t\t            <option value=\"CY\">Cyprus</option>\r\n");
      out.write("\t\t            <option value=\"CZ\">Czech Republic</option>\r\n");
      out.write("\t\t            <option value=\"DK\">Denmark</option>\r\n");
      out.write("\t\t            <option value=\"DJ\">Djibouti</option>\r\n");
      out.write("\t\t            <option value=\"DM\">Dominica</option>\r\n");
      out.write("\t\t            <option value=\"DO\">Dominican Republic</option>\r\n");
      out.write("\t\t            <option value=\"TP\">East Timor</option>\r\n");
      out.write("\t\t            <option value=\"EC\">Ecuador</option>\r\n");
      out.write("\t\t            <option value=\"EG\">Egypt</option>\r\n");
      out.write("\t\t            <option value=\"SV\">El Salvador</option>\r\n");
      out.write("\t\t            <option value=\"GQ\">Equatorial Guinea</option>\r\n");
      out.write("\t\t            <option value=\"ER\">Eritrea</option>\r\n");
      out.write("\t\t            <option value=\"EE\">Estonia</option>\r\n");
      out.write("\t\t            <option value=\"ET\">Ethiopia</option>\r\n");
      out.write("\t\t            <option value=\"FK\">Falkland Islands (Islas Malvinas)</option>\r\n");
      out.write("\t\t            <option value=\"FO\">Faroe Islands</option>\r\n");
      out.write("\t\t            <option value=\"FJ\">Fiji Islands</option>\r\n");
      out.write("\t\t            <option value=\"FI\">Finland</option>\r\n");
      out.write("\t\t            <option value=\"FR\">France</option>\r\n");
      out.write("\t\t            <option value=\"FX\">France, Metropolitan</option>\r\n");
      out.write("\t\t            <option value=\"GF\">French Guiana</option>\r\n");
      out.write("\t\t            <option value=\"PF\">French Polynesia</option>\r\n");
      out.write("\t\t            <option value=\"TF\">French Southern Territories</option>\r\n");
      out.write("\t\t            <option value=\"GA\">Gabon</option>\r\n");
      out.write("\t\t            <option value=\"GM\">Gambia, The</option>\r\n");
      out.write("\t\t            <option value=\"GE\">Georgia</option>\r\n");
      out.write("\t\t            <option value=\"DE\">Germany</option>\r\n");
      out.write("\t\t            <option value=\"GH\">Ghana</option>\r\n");
      out.write("\t\t            <option value=\"GI\">Gibraltar</option>\r\n");
      out.write("\t\t            <option value=\"GR\">Greece</option>\r\n");
      out.write("\t\t            <option value=\"GL\">Greenland</option>\r\n");
      out.write("\t\t            <option value=\"GD\">Grenada</option>\r\n");
      out.write("\t\t            <option value=\"GP\">Guadeloupe</option>\r\n");
      out.write("\t\t            <option value=\"GU\">Guam</option>\r\n");
      out.write("\t\t            <option value=\"GT\">Guatemala</option>\r\n");
      out.write("\t\t            <option value=\"GG\">Guernsey</option>\r\n");
      out.write("\t\t            <option value=\"GN\">Guinea</option>\r\n");
      out.write("\t\t            <option value=\"GW\">Guinea-Bissau</option>\r\n");
      out.write("\t\t            <option value=\"GY\">Guyana</option>\r\n");
      out.write("\t\t            <option value=\"HT\">Haiti</option>\r\n");
      out.write("\t\t            <option value=\"HM\">Heard and McDonald Islands</option>\r\n");
      out.write("\t\t            <option value=\"HN\">Honduras</option>\r\n");
      out.write("\t\t            <option value=\"HK\">Hong Kong S.A.R.</option>\r\n");
      out.write("\t\t            <option value=\"HU\">Hungary</option>\r\n");
      out.write("\t\t            <option value=\"IS\">Iceland</option>\r\n");
      out.write("\t\t            <option value=\"IN\">India</option>\r\n");
      out.write("\t\t            <option value=\"ID\">Indonesia</option>\r\n");
      out.write("\t\t            <option value=\"IR\">Iran</option>\r\n");
      out.write("\t\t            <option value=\"IQ\">Iraq</option>\r\n");
      out.write("\t\t            <option value=\"IE\">Ireland</option>\r\n");
      out.write("\t\t            <option value=\"IM\">Isle of Man</option>\r\n");
      out.write("\t\t            <option value=\"IL\">Israel</option>\r\n");
      out.write("\t\t            <option value=\"IT\">Italy</option>\r\n");
      out.write("\t\t            <option value=\"JM\">Jamaica</option>\r\n");
      out.write("\t\t            <option value=\"JP\">Japan</option>\r\n");
      out.write("\t\t            <option value=\"JE\">Jersey</option>\r\n");
      out.write("\t\t            <option value=\"JO\">Jordan</option>\r\n");
      out.write("\t\t            <option value=\"KZ\">Kazakhstan</option>\r\n");
      out.write("\t\t            <option value=\"KE\">Kenya</option>\r\n");
      out.write("\t\t            <option value=\"KI\">Kiribati</option>\r\n");
      out.write("\t\t            <option value=\"KR\">Korea</option>\r\n");
      out.write("\t\t            <option value=\"KP\">Korea, North</option>\r\n");
      out.write("\t\t            <option value=\"KW\">Kuwait</option>\r\n");
      out.write("\t\t            <option value=\"KG\">Kyrgyzstan</option>\r\n");
      out.write("\t\t            <option value=\"LA\">Laos</option>\r\n");
      out.write("\t\t            <option value=\"LV\">Latvia</option>\r\n");
      out.write("\t\t            <option value=\"LB\">Lebanon</option>\r\n");
      out.write("\t\t            <option value=\"LS\">Lesotho</option>\r\n");
      out.write("\t\t            <option value=\"LR\">Liberia</option>\r\n");
      out.write("\t\t            <option value=\"LY\">Libya</option>\r\n");
      out.write("\t\t            <option value=\"LI\">Liechtenstein</option>\r\n");
      out.write("\t\t            <option value=\"LT\">Lithuania</option>\r\n");
      out.write("\t\t            <option value=\"LU\">Luxembourg</option>\r\n");
      out.write("\t\t            <option value=\"MO\">Macau S.A.R.</option>\r\n");
      out.write("\t\t            <option value=\"MK\">Macedonia</option>\r\n");
      out.write("\t\t            <option value=\"MG\">Madagascar</option>\r\n");
      out.write("\t\t            <option value=\"MW\">Malawi</option>\r\n");
      out.write("\t\t            <option value=\"MY\">Malaysia</option>\r\n");
      out.write("\t\t            <option value=\"MV\">Maldives</option>\r\n");
      out.write("\t\t            <option value=\"ML\">Mali</option>\r\n");
      out.write("\t\t            <option value=\"MT\">Malta</option>\r\n");
      out.write("\t\t            <option value=\"MH\">Marshall Islands</option>\r\n");
      out.write("\t\t            <option value=\"MQ\">Martinique</option>\r\n");
      out.write("\t\t            <option value=\"MR\">Mauritania</option>\r\n");
      out.write("\t\t            <option value=\"MU\">Mauritius</option>\r\n");
      out.write("\t\t            <option value=\"YT\">Mayotte</option>\r\n");
      out.write("\t\t            <option value=\"MX\">Mexico</option>\r\n");
      out.write("\t\t            <option value=\"FM\">Micronesia</option>\r\n");
      out.write("\t\t            <option value=\"MD\">Moldova</option>\r\n");
      out.write("\t\t            <option value=\"MC\">Monaco</option>\r\n");
      out.write("\t\t            <option value=\"MN\">Mongolia</option>\r\n");
      out.write("\t\t            <option value=\"ME\">Montenegro</option>\r\n");
      out.write("\t\t            <option value=\"MS\">Montserrat</option>\r\n");
      out.write("\t\t            <option value=\"MA\">Morocco</option>\r\n");
      out.write("\t\t            <option value=\"MZ\">Mozambique</option>\r\n");
      out.write("\t\t            <option value=\"MM\">Myanmar</option>\r\n");
      out.write("\t\t            <option value=\"NA\">Namibia</option>\r\n");
      out.write("\t\t            <option value=\"NR\">Nauru</option>\r\n");
      out.write("\t\t            <option value=\"NP\">Nepal</option>\r\n");
      out.write("\t\t            <option value=\"NL\">Netherlands</option>\r\n");
      out.write("\t\t            <option value=\"AN\">Netherlands Antilles</option>\r\n");
      out.write("\t\t            <option value=\"NC\">New Caledonia</option>\r\n");
      out.write("\t\t            <option value=\"NZ\">New Zealand</option>\r\n");
      out.write("\t\t            <option value=\"NI\">Nicaragua</option>\r\n");
      out.write("\t\t            <option value=\"NE\">Niger</option>\r\n");
      out.write("\t\t            <option value=\"NG\">Nigeria</option>\r\n");
      out.write("\t\t            <option value=\"NU\">Niue</option>\r\n");
      out.write("\t\t            <option value=\"NF\">Norfolk Island</option>\r\n");
      out.write("\t\t            <option value=\"MP\">Northern Mariana Islands</option>\r\n");
      out.write("\t\t            <option value=\"NO\">Norway</option>\r\n");
      out.write("\t\t            <option value=\"OM\">Oman</option>\r\n");
      out.write("\t\t            <option value=\"PK\">Pakistan</option>\r\n");
      out.write("\t\t            <option value=\"PW\">Palau</option>\r\n");
      out.write("\t\t            <option value=\"PS\">Palestinian Territory, Occupied</option>\r\n");
      out.write("\t\t            <option value=\"PA\">Panama</option>\r\n");
      out.write("\t\t            <option value=\"PG\">Papua new Guinea</option>\r\n");
      out.write("\t\t            <option value=\"PY\">Paraguay</option>\r\n");
      out.write("\t\t            <option value=\"PE\">Peru</option>\r\n");
      out.write("\t\t            <option value=\"PH\">Philippines</option>\r\n");
      out.write("\t\t            <option value=\"PN\">Pitcairn Island</option>\r\n");
      out.write("\t\t            <option value=\"PL\">Poland</option>\r\n");
      out.write("\t\t            <option value=\"PT\">Portugal</option>\r\n");
      out.write("\t\t            <option value=\"PR\">Puerto Rico</option>\r\n");
      out.write("\t\t            <option value=\"QA\">Qatar</option>\r\n");
      out.write("\t\t            <option value=\"RE\">Reunion</option>\r\n");
      out.write("\t\t            <option value=\"RO\">Romania</option>\r\n");
      out.write("\t\t            <option value=\"RU\">Russia</option>\r\n");
      out.write("\t\t            <option value=\"RW\">Rwanda</option>\r\n");
      out.write("\t\t            <option value=\"SH\">Saint Helena</option>\r\n");
      out.write("\t\t            <option value=\"KN\">Saint Kitts And Nevis</option>\r\n");
      out.write("\t\t            <option value=\"LC\">Saint Lucia</option>\r\n");
      out.write("\t\t            <option value=\"PM\">Saint Pierre and Miquelon</option>\r\n");
      out.write("\t\t            <option value=\"VC\">Saint Vincent And The Grenadines</option>\r\n");
      out.write("\t\t            <option value=\"WS\">Samoa</option>\r\n");
      out.write("\t\t            <option value=\"SM\">San Marino</option>\r\n");
      out.write("\t\t            <option value=\"ST\">Sao Tome and Principe</option>\r\n");
      out.write("\t\t            <option value=\"SA\">Saudi Arabia</option>\r\n");
      out.write("\t\t            <option value=\"SN\">Senegal</option>\r\n");
      out.write("\t\t         </select></div>\t\t        \r\n");
      out.write("\t\t          <div><input type=\"text\" value=\"City\" onfocus=\"this.value = '';\" onblur=\"if (this.value == '') {this.value = 'City';}\"></div>\r\n");
      out.write("\t\t             <input type=\"text\" value=\"\" class=\"code\"> - <input type=\"text\" value=\"\" class=\"number\">\r\n");
      out.write("\t\t          \t <p class=\"code\">Country Code + Phone Number</p>\r\n");
      out.write("\t\t          </div>\r\n");
      out.write("\t\t         <button class=\"grey\">Submit</button>\r\n");
      out.write("\t\t         <p class=\"terms\">By clicking 'Create Account' you agree to the <a href=\"#\">Terms &amp; Conditions</a>.</p>\r\n");
      out.write("\t\t         <div class=\"clear\"></div>\r\n");
      out.write("\t\t    </form>\r\n");
      out.write("    \t  </div> \r\n");
      out.write("        </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
