/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.33
 * Generated at: 2020-06-11 18:35:54 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.user;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class shop_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/views/layouts/user/taglib.jsp", Long.valueOf(1591820222862L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1582398222332L));
    _jspx_dependants.put("jar:file:/E:/Hoc-tren-lop-ky-7/1_BTL_JAVANANGCAO/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/ShoesSore/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153359882000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fend_005fbegin;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fend_005fbegin = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fend_005fbegin.release();
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("    ");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Shop</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"login\">\r\n");
      out.write("\t\t<div class=\"wrap\">\r\n");
      out.write("\t\t\t<div class=\"rsidebar span_1_of_left\">\r\n");
      out.write("\t\t\t\t<section class=\"sky-form\">\r\n");
      out.write("\t\t\t\t\t<h4>Occasion</h4>\r\n");
      out.write("\t\t\t\t\t<div class=\"row row1 scroll-pane\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col col-4\">\r\n");
      out.write("\t\t\t\t\t\t\t<label class=\"checkbox\"><input type=\"checkbox\"\r\n");
      out.write("\t\t\t\t\t\t\t\tname=\"checkbox\" checked=\"\"><i></i>Athletic (20)</label>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col col-4\">\r\n");
      out.write("\t\t\t\t\t\t\t<label class=\"checkbox\"><input type=\"checkbox\"\r\n");
      out.write("\t\t\t\t\t\t\t\tname=\"checkbox\"><i></i>Athletic Shoes (48)</label> <label\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"checkbox\"><input type=\"checkbox\" name=\"checkbox\"><i></i>Casual\r\n");
      out.write("\t\t\t\t\t\t\t\t(45)</label> <label class=\"checkbox\"><input type=\"checkbox\"\r\n");
      out.write("\t\t\t\t\t\t\t\tname=\"checkbox\"><i></i>Casual (45)</label> <label\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"checkbox\"><input type=\"checkbox\" name=\"checkbox\"><i></i>Other\r\n");
      out.write("\t\t\t\t\t\t\t\t(1)</label>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<h4>Category</h4>\r\n");
      out.write("\t\t\t\t\t<div class=\"row row1 scroll-pane\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col col-4\">\r\n");
      out.write("\t\t\t\t\t\t\t<label class=\"checkbox\"><input type=\"checkbox\"\r\n");
      out.write("\t\t\t\t\t\t\t\tname=\"checkbox\" checked=\"\"><i></i>Flats (70)</label>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col col-4\">\r\n");
      out.write("\t\t\t\t\t\t\t<label class=\"checkbox\"><input type=\"checkbox\"\r\n");
      out.write("\t\t\t\t\t\t\t\tname=\"checkbox\"><i></i>Athletic Shoes (48)</label> <label\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"checkbox\"><input type=\"checkbox\" name=\"checkbox\"><i></i>Athletic\r\n");
      out.write("\t\t\t\t\t\t\t\tShoes (48)</label> <label class=\"checkbox\"><input\r\n");
      out.write("\t\t\t\t\t\t\t\ttype=\"checkbox\" name=\"checkbox\"><i></i>Heels (38)</label> <label\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"checkbox\"><input type=\"checkbox\" name=\"checkbox\"><i></i>Other\r\n");
      out.write("\t\t\t\t\t\t\t\t(1)</label>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<h4>Styles</h4>\r\n");
      out.write("\t\t\t\t\t<div class=\"row row1 scroll-pane\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col col-4\">\r\n");
      out.write("\t\t\t\t\t\t\t<label class=\"checkbox\"><input type=\"checkbox\"\r\n");
      out.write("\t\t\t\t\t\t\t\tname=\"checkbox\" checked=\"\"><i></i>Athletic (20)</label>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col col-4\">\r\n");
      out.write("\t\t\t\t\t\t\t<label class=\"checkbox\"><input type=\"checkbox\"\r\n");
      out.write("\t\t\t\t\t\t\t\tname=\"checkbox\"><i></i>Ballerina (5)</label> <label\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"checkbox\"><input type=\"checkbox\" name=\"checkbox\"><i></i>Pumps\r\n");
      out.write("\t\t\t\t\t\t\t\t(7)</label> <label class=\"checkbox\"><input type=\"checkbox\"\r\n");
      out.write("\t\t\t\t\t\t\t\tname=\"checkbox\"><i></i>High Tops (2)</label> <label\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"checkbox\"><input type=\"checkbox\" name=\"checkbox\"><i></i>Other\r\n");
      out.write("\t\t\t\t\t\t\t\t(1)</label>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</section>\r\n");
      out.write("\t\t\t\t<section class=\"sky-form\">\r\n");
      out.write("\t\t\t\t\t<h4>Brand</h4>\r\n");
      out.write("\t\t\t\t\t<div class=\"row row1 scroll-pane\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col col-4\">\r\n");
      out.write("\t\t\t\t\t\t\t<label class=\"checkbox\"><input type=\"checkbox\"\r\n");
      out.write("\t\t\t\t\t\t\t\tname=\"checkbox\" checked=\"\"><i></i>Adidas by Stella\r\n");
      out.write("\t\t\t\t\t\t\t\tMcCartney</label>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col col-4\">\r\n");
      out.write("\t\t\t\t\t\t\t<label class=\"checkbox\"><input type=\"checkbox\"\r\n");
      out.write("\t\t\t\t\t\t\t\tname=\"checkbox\"><i></i>Asics</label> <label class=\"checkbox\"><input\r\n");
      out.write("\t\t\t\t\t\t\t\ttype=\"checkbox\" name=\"checkbox\"><i></i>Bloch</label> <label\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"checkbox\"><input type=\"checkbox\" name=\"checkbox\"><i></i>Bloch\r\n");
      out.write("\t\t\t\t\t\t\t\tKids</label> <label class=\"checkbox\"><input type=\"checkbox\"\r\n");
      out.write("\t\t\t\t\t\t\t\tname=\"checkbox\"><i></i>Capezio</label> <label class=\"checkbox\"><input\r\n");
      out.write("\t\t\t\t\t\t\t\ttype=\"checkbox\" name=\"checkbox\"><i></i>Capezio Kids</label> <label\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"checkbox\"><input type=\"checkbox\" name=\"checkbox\"><i></i>Nike</label>\r\n");
      out.write("\t\t\t\t\t\t\t<label class=\"checkbox\"><input type=\"checkbox\"\r\n");
      out.write("\t\t\t\t\t\t\t\tname=\"checkbox\"><i></i>Zumba</label>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</section>\r\n");
      out.write("\t\t\t\t<section class=\"sky-form\">\r\n");
      out.write("\t\t\t\t\t<h4>Heel Height</h4>\r\n");
      out.write("\t\t\t\t\t<div class=\"row row1 scroll-pane\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col col-4\">\r\n");
      out.write("\t\t\t\t\t\t\t<label class=\"checkbox\"><input type=\"checkbox\"\r\n");
      out.write("\t\t\t\t\t\t\t\tname=\"checkbox\" checked=\"\"><i></i>Flat (20)</label>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col col-4\">\r\n");
      out.write("\t\t\t\t\t\t\t<label class=\"checkbox\"><input type=\"checkbox\"\r\n");
      out.write("\t\t\t\t\t\t\t\tname=\"checkbox\"><i></i>Under 1in(5)</label> <label\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"checkbox\"><input type=\"checkbox\" name=\"checkbox\"><i></i>1in\r\n");
      out.write("\t\t\t\t\t\t\t\t- 1 3/4 in(5)</label> <label class=\"checkbox\"><input\r\n");
      out.write("\t\t\t\t\t\t\t\ttype=\"checkbox\" name=\"checkbox\"><i></i>2in - 2 3/4 in(3)</label>\r\n");
      out.write("\t\t\t\t\t\t\t<label class=\"checkbox\"><input type=\"checkbox\"\r\n");
      out.write("\t\t\t\t\t\t\t\tname=\"checkbox\"><i></i>3in - 3 3/4 in(2)</label>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</section>\r\n");
      out.write("\t\t\t\t<section class=\"sky-form\">\r\n");
      out.write("\t\t\t\t\t<h4>Price</h4>\r\n");
      out.write("\t\t\t\t\t<div class=\"row row1 scroll-pane\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col col-4\">\r\n");
      out.write("\t\t\t\t\t\t\t<label class=\"checkbox\"><input type=\"checkbox\"\r\n");
      out.write("\t\t\t\t\t\t\t\tname=\"checkbox\" checked=\"\"><i></i>$50.00 and Under (30)</label>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col col-4\">\r\n");
      out.write("\t\t\t\t\t\t\t<label class=\"checkbox\"><input type=\"checkbox\"\r\n");
      out.write("\t\t\t\t\t\t\t\tname=\"checkbox\"><i></i>$100.00 and Under (30)</label> <label\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"checkbox\"><input type=\"checkbox\" name=\"checkbox\"><i></i>$200.00\r\n");
      out.write("\t\t\t\t\t\t\t\tand Under (30)</label> <label class=\"checkbox\"><input\r\n");
      out.write("\t\t\t\t\t\t\t\ttype=\"checkbox\" name=\"checkbox\"><i></i>$300.00 and Under\r\n");
      out.write("\t\t\t\t\t\t\t\t(30)</label> <label class=\"checkbox\"><input type=\"checkbox\"\r\n");
      out.write("\t\t\t\t\t\t\t\tname=\"checkbox\"><i></i>$400.00 and Under (30)</label>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</section>\r\n");
      out.write("\t\t\t\t<section class=\"sky-form\">\r\n");
      out.write("\t\t\t\t\t<h4>Colors</h4>\r\n");
      out.write("\t\t\t\t\t<div class=\"row row1 scroll-pane\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col col-4\">\r\n");
      out.write("\t\t\t\t\t\t\t<label class=\"checkbox\"><input type=\"checkbox\"\r\n");
      out.write("\t\t\t\t\t\t\t\tname=\"checkbox\" checked=\"\"><i></i>Red</label>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col col-4\">\r\n");
      out.write("\t\t\t\t\t\t\t<label class=\"checkbox\"><input type=\"checkbox\"\r\n");
      out.write("\t\t\t\t\t\t\t\tname=\"checkbox\"><i></i>Green</label> <label class=\"checkbox\"><input\r\n");
      out.write("\t\t\t\t\t\t\t\ttype=\"checkbox\" name=\"checkbox\"><i></i>Black</label> <label\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"checkbox\"><input type=\"checkbox\" name=\"checkbox\"><i></i>Yellow</label>\r\n");
      out.write("\t\t\t\t\t\t\t<label class=\"checkbox\"><input type=\"checkbox\"\r\n");
      out.write("\t\t\t\t\t\t\t\tname=\"checkbox\"><i></i>Orange</label>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</section>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"cont span_2_of_3\">\r\n");
      out.write("\t\t\t\t<div class=\"mens-toolbar\">\r\n");
      out.write("\t\t\t\t\t<div class=\"sort\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"sort-by\">\r\n");
      out.write("\t\t\t\t\t\t\t<label>Sắp xếp theo</label> <select>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"\">Phổ biến</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"\">Giá: Cao đến thấp</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"\">Giá: Thấp đến cao</option>\r\n");
      out.write("\t\t\t\t\t\t\t</select> <a href=\"\"><img src=\"images/arrow2.gif\" alt=\"\"\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"v-middle\"></a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"pager\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"limiter visible-desktop\">\r\n");
      out.write("\t\t\t\t\t\t\t<label>Hiển thị</label> <select>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"\" selected=\"selected\">9</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"\">15</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"\">30</option>\r\n");
      out.write("\t\t\t\t\t\t\t</select> mỗi trang\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"dc_pagination dc_paginationA dc_paginationA06\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\" class=\"previous\">Trang</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t");
      if (_jspx_meth_c_005fforEach_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"clear\"></div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"clear\"></div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t");
      if (_jspx_meth_c_005fforEach_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"clear\"></div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /WEB-INF/views/user/shop.jsp(11,1) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("item");
      // /WEB-INF/views/user/shop.jsp(11,1) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/user/shop.jsp(11,1) '${sanphamtheoloaiModel}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${sanphamtheoloaiModel}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t\t<h1>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.tensanpham }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</h1>\r\n");
            out.write("\t");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fend_005fbegin.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f1_reused = false;
    try {
      _jspx_th_c_005fforEach_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f1.setParent(null);
      // /WEB-INF/views/user/shop.jsp(166,7) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setVar("item");
      // /WEB-INF/views/user/shop.jsp(166,7) name = begin type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setBegin(1);
      // /WEB-INF/views/user/shop.jsp(166,7) name = end type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setEnd(((java.lang.Integer) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ phantrangModel.totalPage}", int.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).intValue());
      // /WEB-INF/views/user/shop.jsp(166,7) name = varStatus type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setVarStatus("loop");
      int[] _jspx_push_body_count_c_005fforEach_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f1 = _jspx_th_c_005fforEach_005f1.doStartTag();
        if (_jspx_eval_c_005fforEach_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t\t\t\t\t\t\t\r\n");
            out.write("\t\t\t\t\t\t\r\n");
            out.write("\t\t\t\t\t\t\t\t<li><a\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\thref=\"");
            if (_jspx_meth_c_005furl_005f0(_jspx_th_c_005fforEach_005f1, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f1))
              return true;
            out.write("\">\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loop.index }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</a></li>\r\n");
            out.write("\t\t\t\t\t\t\t\r\n");
            out.write("\t\t\t\t\t<!-- \t\t<li><a href=\"#\" class =\"active\">1</a></li>\r\n");
            out.write("\t\t\t\t\t\t\t<li><a href=\"#\">2</a></li> -->\r\n");
            out.write("\t\t\t\t\t\t\t");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f1.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fend_005fbegin.reuse(_jspx_th_c_005fforEach_005f1);
      _jspx_th_c_005fforEach_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f1, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f1)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f0 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f0_reused = false;
    try {
      _jspx_th_c_005furl_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f1);
      // /WEB-INF/views/user/shop.jsp(170,16) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f0.setValue((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("/shop/${idloaisanpham}/${loop.index}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005furl_005f0 = _jspx_th_c_005furl_005f0.doStartTag();
      if (_jspx_th_c_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
      _jspx_th_c_005furl_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f0, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f2 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f2_reused = false;
    try {
      _jspx_th_c_005fforEach_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f2.setParent(null);
      // /WEB-INF/views/user/shop.jsp(183,4) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f2.setVar("item");
      // /WEB-INF/views/user/shop.jsp(183,4) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f2.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/user/shop.jsp(183,4) '${sanphamtheoloaiModel }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${sanphamtheoloaiModel }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f2 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f2 = _jspx_th_c_005fforEach_005f2.doStartTag();
        if (_jspx_eval_c_005fforEach_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t\t\t\t<div class=\"box1\">\r\n");
            out.write("\t\t\t\t\t<div class=\"col_1_of_single1 span_1_of_single1\">\r\n");
            out.write("\t\t\t\t\t\t<a href=\"single.html\">\r\n");
            out.write("\t\t\t\t\t\t\t<div class=\"view1 view-fifth1\">\r\n");
            out.write("\t\t\t\t\t\t\t\t<div class=\"top_box\">\r\n");
            out.write("\t\t\t\t\t\t\t\t\t<h3 class=\"m_1\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.tensanpham}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</h3>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t<p class=\"m_2\">Lorem ipsum</p>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t<div class=\"grid_img\">\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"css3\">\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t<img src=\"");
            if (_jspx_meth_c_005furl_005f1(_jspx_th_c_005fforEach_005f2, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f2))
              return true;
            out.write("\" alt=\"\" />\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"mask1\">\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"info\">Quick View</div>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t<div class=\"price\">£480</div>\r\n");
            out.write("\t\t\t\t\t\t\t\t</div>\r\n");
            out.write("\t\t\t\t\t\t\t</div> <span class=\"rating1\"> <input type=\"radio\"\r\n");
            out.write("\t\t\t\t\t\t\t\tclass=\"rating-input\" id=\"rating-input-1-5\" name=\"rating-input-1\">\r\n");
            out.write("\t\t\t\t\t\t\t\t<label for=\"rating-input-1-5\" class=\"rating-star1\"></label> <input\r\n");
            out.write("\t\t\t\t\t\t\t\ttype=\"radio\" class=\"rating-input\" id=\"rating-input-1-4\"\r\n");
            out.write("\t\t\t\t\t\t\t\tname=\"rating-input-1\"> <label for=\"rating-input-1-4\"\r\n");
            out.write("\t\t\t\t\t\t\t\tclass=\"rating-star1\"></label> <input type=\"radio\"\r\n");
            out.write("\t\t\t\t\t\t\t\tclass=\"rating-input\" id=\"rating-input-1-3\" name=\"rating-input-1\">\r\n");
            out.write("\t\t\t\t\t\t\t\t<label for=\"rating-input-1-3\" class=\"rating-star1\"></label> <input\r\n");
            out.write("\t\t\t\t\t\t\t\ttype=\"radio\" class=\"rating-input\" id=\"rating-input-1-2\"\r\n");
            out.write("\t\t\t\t\t\t\t\tname=\"rating-input-1\"> <label for=\"rating-input-1-2\"\r\n");
            out.write("\t\t\t\t\t\t\t\tclass=\"rating-star\"></label> <input type=\"radio\"\r\n");
            out.write("\t\t\t\t\t\t\t\tclass=\"rating-input\" id=\"rating-input-1-1\" name=\"rating-input-1\">\r\n");
            out.write("\t\t\t\t\t\t\t\t<label for=\"rating-input-1-1\" class=\"rating-star\"></label>&nbsp;\r\n");
            out.write("\t\t\t\t\t\t\t\t(45)\r\n");
            out.write("\t\t\t\t\t\t</span>\r\n");
            out.write("\t\t\t\t\t\t\t<ul class=\"list2\">\r\n");
            out.write("\t\t\t\t\t\t\t\t<li><img src=\"images/plus.png\" alt=\"\" />\r\n");
            out.write("\t\t\t\t\t\t\t\t\t<ul class=\"icon1 sub-icon1 profile_img\">\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<li><a class=\"active-icon c1\" href=\"#\">Add To Bag </a>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t<ul class=\"sub-icon1 list\">\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t<li><h3>sed diam nonummy</h3>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"\"></a></li>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t<li><p>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tLorem ipsum dolor sit amet, consectetuer <a href=\"\">adipiscing\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\telit, sed diam</a>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</p></li>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t</ul></li>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t</ul></li>\r\n");
            out.write("\t\t\t\t\t\t\t</ul>\r\n");
            out.write("\t\t\t\t\t\t\t<div class=\"clear\"></div>\r\n");
            out.write("\t\t\t\t\t\t</a>\r\n");
            out.write("\t\t\t\t\t</div>\r\n");
            out.write("\t\t\t\t\r\n");
            out.write("\t\t\t\t\t\r\n");
            out.write("\t\t\t\t\t<div class=\"clear\"></div>\r\n");
            out.write("\t\t\t\t</div>\r\n");
            out.write("\t\t\t\t");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f2.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f2[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f2.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f2.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f2);
      _jspx_th_c_005fforEach_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f2, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f2)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f1 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f1_reused = false;
    try {
      _jspx_th_c_005furl_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f2);
      // /WEB-INF/views/user/shop.jsp(193,21) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f1.setValue((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("/assets/user/images/myimages/${item.link1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005furl_005f1 = _jspx_th_c_005furl_005f1.doStartTag();
      if (_jspx_th_c_005furl_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f1);
      _jspx_th_c_005furl_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f1, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f1_reused);
    }
    return false;
  }
}
